version: "3.0"
services:
  userDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
  user-service:
    build:
      context: ../services/user-service
      dockerfile: ./DockerFile
    environment:
      - DB_HOST=userDB
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET=SECRET
    ports:
      - "5000:5000"
    networks:
      - custom
  spotDB:
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
  spot-service:
    build:
      context: ../services/spot-service
      dockerfile: ./DockerFile
    environment:
      - POSTGRES_DSN=postgresql://postgres:postgres@spotDB:5432/postgres
    ports:
      - "5001:5001"
    networks:
      - custom
  matchDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    networks:
      - custom
  match-service:
    build:
      context: ../services/match-service
      dockerfile: ./DockerFile
    environment:
      - POSTGRES_DSN=postgresql://postgres:postgres@matchDB:5432/postgres
    ports:
      - "5002:5002"
    networks:
      - custom
  teamDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5435:5432"
    networks:
      - custom
  # team-service:
  #   build:
  #     context: ../services/match-service
  #     dockerfile: ./DockerFile
  #   environment:
  #     - POSTGRES_DSN=postgresql://postgres:postgres@matchDB:5432/postgres
  #   ports:
  #     - "5002:5002"
  #   networks:
  #     - custom
networks:
  custom:
    driver: bridge