version: "3.0"
services:
  db:
    container_name: "userDB"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
  spot-db:
    container_name: "spotDB"
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
  user-service:
    build:
      context: ../services/user-service
      dockerfile: ./DockerFile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET=SECRET
    ports:
      - "5000:5000"
    networks:
      - custom
networks:
  custom:
    driver: bridge
