
FROM python:3.13.0a4-slim

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app
COPY .env ./app/.env
EXPOSE 4999

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "4999","--reload"]