{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(http_requests_total[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "{{ status }}" }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"user-service:5000\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"spot-service:5001\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"team-service:5003\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"match-service:5002\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"Spot-service\"}"
    },
    {
     "expr": "{service=\"Spot-service\"}"
    },
    {
     "expr": "{service=\"Team-service\"}"
    },
    {
     "expr": "{service=\"User-service\"}"
    }
   ]
  },
  {
   "title": "Up status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "up{instance=\"user-service:5000\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{instance=\"spot-service:5001\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{instance=\"match-service:5002\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{instance=\"team-service:5003\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"match-service:5002\"}[30s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"spot-service:5001\"}[30s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"team-service:5003\"}[30s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"user-service:5000\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}